/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trank
 */
import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

public class addnewpatient extends javax.swing.JFrame {

    /**
     * Creates new form addnewpatient
     */
    public addnewpatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseAddPatientBtn = new javax.swing.JButton();
        PatientIDLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        AllergiesLabel = new javax.swing.JLabel();
        PatientIDTxt = new javax.swing.JTextField();
        NameTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        AgeTxt = new javax.swing.JTextField();
        GenderBox = new javax.swing.JComboBox<>();
        AddressTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllergiesTxt = new javax.swing.JTextArea();
        SavePatientBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 120));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(513, 535));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseAddPatientBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CloseAddPatientBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\trank\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\HMS ICON\\Close.png")); // NOI18N
        CloseAddPatientBtn.setText("Close");
        CloseAddPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseAddPatientBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseAddPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        PatientIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PatientIDLabel.setForeground(new java.awt.Color(102, 0, 102));
        PatientIDLabel.setText("Patient ID");
        getContentPane().add(PatientIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 70, 19));

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(102, 0, 102));
        NameLabel.setText("Name");
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 59, -1));

        PhoneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PhoneLabel.setForeground(new java.awt.Color(102, 0, 102));
        PhoneLabel.setText("Phone");
        getContentPane().add(PhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 59, -1));

        AgeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(102, 0, 102));
        AgeLabel.setText("Age");
        getContentPane().add(AgeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 31, -1));

        GenderLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(102, 0, 102));
        GenderLabel.setText("Gender");
        getContentPane().add(GenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        AddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(102, 0, 102));
        AddressLabel.setText("Address");
        getContentPane().add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        EmailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(102, 0, 102));
        EmailLabel.setText("Email");
        getContentPane().add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        AllergiesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AllergiesLabel.setForeground(new java.awt.Color(102, 0, 102));
        AllergiesLabel.setText("Allergies");
        getContentPane().add(AllergiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 60, -1));

        PatientIDTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PatientIDTxt.setPreferredSize(new java.awt.Dimension(40, 21));
        getContentPane().add(PatientIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 270, -1));

        NameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NameTxt.setPreferredSize(new java.awt.Dimension(40, 21));
        getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 270, -1));

        PhoneTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PhoneTxt.setPreferredSize(new java.awt.Dimension(40, 21));
        getContentPane().add(PhoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, -1));

        AgeTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AgeTxt.setPreferredSize(new java.awt.Dimension(40, 21));
        getContentPane().add(AgeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 270, -1));

        GenderBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(GenderBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, -1));

        AddressTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(AddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 270, -1));

        EmailTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(EmailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 270, -1));

        AllergiesTxt.setColumns(20);
        AllergiesTxt.setRows(5);
        jScrollPane1.setViewportView(AllergiesTxt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 360, 120));

        SavePatientBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SavePatientBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\trank\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\HMS ICON\\save-icon--1.png")); // NOI18N
        SavePatientBtn.setText(" Save");
        SavePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePatientBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SavePatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("Add new patient");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\trank\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\HMS ICON\\bg.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseAddPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseAddPatientBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseAddPatientBtnActionPerformed

    private void SavePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePatientBtnActionPerformed
        // TODO add your handling code here:
        String patientID = PatientIDTxt.getText();
        String name= NameTxt.getText();
        String phone = PhoneTxt.getText();
        String gender =(String)GenderBox.getSelectedItem();
        String address= AddressTxt.getText();
        int age = Integer.parseInt(AgeTxt.getText());
        String email = EmailTxt.getText();
        String allergies=AllergiesTxt.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st= con.createStatement();
            st.executeUpdate("insert into patient values('"+patientID+"', '"+name+"','"+phone+"','"+age+"','"+gender+"','"+address+"','"+allergies+"','"+email+"')");
            JOptionPane.showMessageDialog(null,"Succesfully Inserted");
            setVisible(false);
            new addnewpatient().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please enter in a correct format");
        }
    }//GEN-LAST:event_SavePatientBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addnewpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addnewpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addnewpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addnewpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addnewpatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JLabel AllergiesLabel;
    private javax.swing.JTextArea AllergiesTxt;
    private javax.swing.JButton CloseAddPatientBtn;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PatientIDLabel;
    private javax.swing.JTextField PatientIDTxt;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JButton SavePatientBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
