/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trank
 */
import net.proteanit.sql.DbUtils;
import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;  
import java.util.Date;  

public class addprescription extends javax.swing.JFrame {

    public int flag = 0;
    /**
     * Creates new form add prescription
     */
    public addprescription() {
        initComponents();
        Patientnotexisted.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        PatientIDSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientTable = new javax.swing.JTable();
        Patientnotexisted = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        DiagnosisLabel = new javax.swing.JLabel();
        MedicineLabel = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        DateChooserBox = new com.toedter.calendar.JDateChooser();
        NoteLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DiagnosisTxt = new javax.swing.JTextArea();
        MedicineTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        NoteTxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 120));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(782, 476));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 67, -1, -1));

        SearchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\trank\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\HMS ICON\\search.png")); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 61, -1, -1));

        PatientIDSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(PatientIDSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 64, 133, -1));

        PatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PatientTable.setRowHeight(24);
        jScrollPane1.setViewportView(PatientTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 730, 50));

        Patientnotexisted.setForeground(new java.awt.Color(204, 0, 0));
        Patientnotexisted.setText("Patient ID does not exist !");
        getContentPane().add(Patientnotexisted, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 96, 137, -1));

        DateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(51, 0, 153));
        DateLabel.setText("Date");
        getContentPane().add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 40, -1));

        DiagnosisLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiagnosisLabel.setForeground(new java.awt.Color(51, 0, 153));
        DiagnosisLabel.setText("Diagnosis");
        getContentPane().add(DiagnosisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 283, 70, -1));

        MedicineLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MedicineLabel.setForeground(new java.awt.Color(51, 0, 153));
        MedicineLabel.setText("Medicines");
        getContentPane().add(MedicineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 80, 20));

        CloseBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CloseBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\trank\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\HMS ICON\\Close.png")); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SaveBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\trank\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\HMS ICON\\save-icon--1.png")); // NOI18N
        SaveBtn.setText(" Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        getContentPane().add(DateChooserBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 340, 30));

        NoteLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NoteLabel.setForeground(new java.awt.Color(51, 0, 153));
        NoteLabel.setText("Doctor Note");
        getContentPane().add(NoteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, 20));

        DiagnosisTxt.setColumns(20);
        DiagnosisTxt.setRows(5);
        jScrollPane2.setViewportView(DiagnosisTxt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 340, 80));
        getContentPane().add(MedicineTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 360, 30));

        NoteTxt.setColumns(20);
        NoteTxt.setRows(5);
        jScrollPane3.setViewportView(NoteTxt);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 360, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\trank\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\HMS ICON\\bg.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        String patientID= PatientIDSearch.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("select * from patient where patientID='"+patientID+"'");
            PatientTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            if(!rs.first())
                Patientnotexisted.setVisible(true);
            else
            {
                Patientnotexisted.setVisible(false); 
                PatientIDSearch.setEditable(false);
                flag=1;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        
        if (flag ==1){
            String patientID = PatientIDSearch.getText();
            String diagnosis= DiagnosisTxt.getText();
            String medicines=MedicineTxt.getText();
            String note=NoteTxt.getText();
            Date d = DateChooserBox.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date= sdf.format(d);
            
            try {
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                st.executeUpdate("insert into prescription(patientID, diagnosis, date,medicines,note) values('"+patientID+"','"+diagnosis+"','"+date+"','"+medicines+"','"+note+"')");
                JOptionPane.showMessageDialog(null,"Successfully Updated");
                setVisible(false);
                new addprescription().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
        else
            JOptionPane.showMessageDialog(null,"Patient ID Field is empty");
    }//GEN-LAST:event_SaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addprescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addprescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addprescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addprescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addprescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private com.toedter.calendar.JDateChooser DateChooserBox;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel DiagnosisLabel;
    private javax.swing.JTextArea DiagnosisTxt;
    private javax.swing.JLabel MedicineLabel;
    private javax.swing.JTextField MedicineTxt;
    private javax.swing.JLabel NoteLabel;
    private javax.swing.JTextArea NoteTxt;
    private javax.swing.JTextField PatientIDSearch;
    private javax.swing.JTable PatientTable;
    private javax.swing.JLabel Patientnotexisted;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
