
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trank
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPatientBtn = new javax.swing.JButton();
        UpdatePatientBtn = new javax.swing.JButton();
        ViewAppBtn = new javax.swing.JButton();
        ScheduleAppBtn = new javax.swing.JButton();
        AddDiaBtn = new javax.swing.JButton();
        PatientHistoryBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        HomeBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPatientBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddPatientBtn.setForeground(new java.awt.Color(102, 0, 153));
        AddPatientBtn.setText("  Add new patient");
        AddPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 55));

        UpdatePatientBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdatePatientBtn.setForeground(new java.awt.Color(102, 0, 153));
        UpdatePatientBtn.setText("Update patient record");
        UpdatePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePatientBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdatePatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, 55));

        ViewAppBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewAppBtn.setForeground(new java.awt.Color(102, 0, 153));
        ViewAppBtn.setText("View appointment");
        ViewAppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAppBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewAppBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 250, 55));

        ScheduleAppBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ScheduleAppBtn.setForeground(new java.awt.Color(102, 0, 153));
        ScheduleAppBtn.setText("Schedule appointment");
        ScheduleAppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleAppBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ScheduleAppBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 250, 55));

        AddDiaBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddDiaBtn.setForeground(new java.awt.Color(102, 0, 153));
        AddDiaBtn.setText("Add Diagnosis");
        AddDiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDiaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddDiaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 250, 55));

        PatientHistoryBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PatientHistoryBtn.setForeground(new java.awt.Color(102, 0, 153));
        PatientHistoryBtn.setText("View all patients");
        PatientHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientHistoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PatientHistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 250, 55));

        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(102, 0, 153));
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 250, 55));

        HomeBg.setIcon(new javax.swing.ImageIcon("C:\\Users\\trank\\OneDrive\\Documents\\NetBeansProjects\\HospitalManagementSystem\\src\\HMS ICON\\homebg.png")); // NOI18N
        getContentPane().add(HomeBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePatientBtnActionPerformed
        // TODO add your handling code here:
       new updatepatientrecord().setVisible(true);
    }//GEN-LAST:event_UpdatePatientBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null,"Do you want to logout","Select",JOptionPane.YES_NO_OPTION);
        if (a ==0)
        {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void AddPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientBtnActionPerformed
        // TODO add your handling code here:
        new addnewpatient().setVisible(true);
    }//GEN-LAST:event_AddPatientBtnActionPerformed

    private void AddDiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDiaBtnActionPerformed
        // TODO add your handling code here:
        new addprescription().setVisible(true);
    }//GEN-LAST:event_AddDiaBtnActionPerformed

    private void PatientHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientHistoryBtnActionPerformed
        // TODO add your handling code here:
        new listpatients().setVisible(true);
    }//GEN-LAST:event_PatientHistoryBtnActionPerformed

    private void ScheduleAppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleAppBtnActionPerformed
        // TODO add your handling code here:
        new scheduleappointment().setVisible(true);
    }//GEN-LAST:event_ScheduleAppBtnActionPerformed

    private void ViewAppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAppBtnActionPerformed
        // TODO add your handling code here:
        
        new ViewSchedule().setVisible(true);
    }//GEN-LAST:event_ViewAppBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDiaBtn;
    private javax.swing.JButton AddPatientBtn;
    private javax.swing.JLabel HomeBg;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton PatientHistoryBtn;
    private javax.swing.JButton ScheduleAppBtn;
    private javax.swing.JButton UpdatePatientBtn;
    private javax.swing.JButton ViewAppBtn;
    // End of variables declaration//GEN-END:variables
}
